apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeprodx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeprodx
  template:
    metadata:
      labels:
        app: nodeprodx
    spec:
      restartPolicy: Always
      containers:
      - name: nodeprodx
        image: joelwembo/nodeprodx:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
            limits:
              memory: 200Mi
              cpu: 500m
            requests:
              cpu: 300m
              memory: 200Mi  
---
# Load Balancer
apiVersion: v1
kind: Service
metadata:  
  name: nodeprodx
spec:
  externalIPs:
  - 20.6.232.125
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: nodeprodx
  type: LoadBalancer
status:
  loadBalancer: {}              