apiVersion: v1
kind: Service
metadata:  
  name: nodeprodx
spec:
  externalIPs:
  - 18.141.186.159
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: nodeprodx
  type: LoadBalancer
status:
  loadBalancer: {}