apiVersion: v1
kind: Service
metadata:  
  name: nodeprodx
spec:
  externalIPs:
  - 20.6.232.125
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: nodeprodx
  type: LoadBalancer
status:
  loadBalancer: {}